# AWS CodeBuild buildspec.yml to specify build commands
version: 0.1

environment_variables:
  plaintext:
    TAR_FILE: ${IMAGE_NAME}.tar.gz

phases:
  install:
    commands:
      - echo Nothing to do in the install phase
      - echo $TAR_FILE
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_NAME .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker save --output $TAR_FILE $IMAGE_NAME
artifacts:
  files:
    - $TAR_FILE
